document.createElement("canvas").getContext||function(){function z(){return this.context_||(this.context_=new l(this))}function C(a,b,c){var d=E.call(arguments,2);return function(){return a.apply(b,d.concat(E.call(arguments)))}}function u(a){var b=a.srcElement;switch(a.propertyName){case "width":b.style.width=b.attributes.width.nodeValue+"px";b.getContext().clearRect();break;case "height":b.style.height=b.attributes.height.nodeValue+"px",b.getContext().clearRect()}}function w(a){a=a.srcElement;a.firstChild&&
(a.firstChild.style.width=a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px")}function y(){return[[1,0,0],[0,1,0],[0,0,1]]}function r(a,b){for(var c=y(),d=0;3>d;d++)for(var g=0;3>g;g++){for(var e=0,f=0;3>f;f++)e+=a[d][f]*b[f][g];c[d][g]=e}return c}function A(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;
b.strokeStyle=a.strokeStyle;b.globalAlpha=a.globalAlpha;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function v(a){var b,c=1;a=String(a);if("rgb"==a.substring(0,3)){b=a.indexOf("(",3);var d=a.indexOf(")",b+1),d=a.substring(b+1,d).split(",");b="#";for(var g=0;3>g;g++)b+=F[Number(d[g])];4==d.length&&"a"==a.substr(3,1)&&(c=d[3])}else b=a;return{color:b,alpha:c}}function e(a){switch(a){case "butt":return"flat";case "round":return"round";default:return"square"}}function l(a){this.m_=
y();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=10;this.globalAlpha=1;this.canvas=a;var b=a.ownerDocument.createElement("div");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";b.style.overflow="hidden";b.style.position="absolute";a.appendChild(b);this.element_=b;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function p(a,b,c,d){a.currentPath_.push({type:"bezierCurveTo",
cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:d.x,y:d.y});a.currentX_=d.x;a.currentY_=d.y}function h(a,b,c){var d;a:{for(d=0;3>d;d++)for(var g=0;2>g;g++)if(!isFinite(b[d][g])||isNaN(b[d][g])){d=!1;break a}d=!0}d&&(a.m_=b,c&&(a.lineScale_=H(I(b[0][0]*b[1][1]-b[0][1]*b[1][0]))))}function q(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function m(){}var t=Math,n=t.round,D=t.sin,x=t.cos,I=t.abs,H=t.sqrt,E=Array.prototype.slice,G={init:function(a){/MSIE/.test(navigator.userAgent)&&
!window.opera&&(a=a||document,a.createElement("canvas"),a.attachEvent("onreadystatechange",C(this.init_,this,a)))},init_:function(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!a.styleSheets.ex_canvas_){var b=a.createStyleSheet();b.owningElement.id="ex_canvas_";b.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}g_o_\\:*{behavior:url(#default#VML)}"}a=
a.getElementsByTagName("canvas");for(b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=z;a.innerHTML="";a.attachEvent("onpropertychange",u);a.attachEvent("onresize",w);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};G.init();for(var F=[],f=0;16>f;f++)for(var B=0;16>B;B++)F[16*f+B]=f.toString(16)+
B.toString(16);f=l.prototype;f.clearRect=function(){this.element_.innerHTML=""};f.beginPath=function(){this.currentPath_=[]};f.moveTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};f.lineTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};f.bezierCurveTo=function(a,b,c,d,g,e){g=this.getCoords_(g,e);a=this.getCoords_(a,b);c=this.getCoords_(c,
d);p(this,a,c,g)};f.quadraticCurveTo=function(a,b,c,d){a=this.getCoords_(a,b);c=this.getCoords_(c,d);d={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};p(this,d,{x:d.x+(c.x-this.currentX_)/3,y:d.y+(c.y-this.currentY_)/3},c)};f.arc=function(a,b,c,d,g,e){c*=10;var f=e?"at":"wa",n=a+x(d)*c-5,l=b+D(d)*c-5;d=a+x(g)*c-5;g=b+D(g)*c-5;n!=d||e||(n+=.125);a=this.getCoords_(a,b);n=this.getCoords_(n,l);d=this.getCoords_(d,g);this.currentPath_.push({type:f,x:a.x,y:a.y,radius:c,
xStart:n.x,yStart:n.y,xEnd:d.x,yEnd:d.y})};f.rect=function(a,b,c,d){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath()};f.strokeRect=function(a,b,c,d){var g=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath();this.stroke();this.currentPath_=g};f.fillRect=function(a,b,c,d){var g=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,
b+d);this.closePath();this.fill();this.currentPath_=g};f.createLinearGradient=function(a,b,c,d){var g=new q("gradient");g.x0_=a;g.y0_=b;g.x1_=c;g.y1_=d;return g};f.createRadialGradient=function(a,b,c,d,g,e){var f=new q("gradientradial");f.x0_=a;f.y0_=b;f.r0_=c;f.x1_=d;f.y1_=g;f.r1_=e;return f};f.drawImage=function(a,b){var c,d,g,e,f,l,p,k;g=a.runtimeStyle.width;e=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var h=a.width,q=a.height;a.runtimeStyle.width=g;a.runtimeStyle.height=
e;if(3==arguments.length)c=arguments[1],d=arguments[2],f=l=0,p=g=h,k=e=q;else if(5==arguments.length)c=arguments[1],d=arguments[2],g=arguments[3],e=arguments[4],f=l=0,p=h,k=q;else if(9==arguments.length)f=arguments[1],l=arguments[2],p=arguments[3],k=arguments[4],c=arguments[5],d=arguments[6],g=arguments[7],e=arguments[8];else throw Error("Invalid number of arguments");var m=this.getCoords_(c,d),r=[];r.push(" <g_vml_:group",' coordsize="',100,",",100,'"',' coordorigin="0,0"',' style="width:',10,"px;height:",
10,"px;position:absolute;");if(1!=this.m_[0][0]||this.m_[0][1]){var v=[];v.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",n(m.x/10),",","Dy=",n(m.y/10),"");var x=this.getCoords_(c+g,d),u=this.getCoords_(c,d+e);c=this.getCoords_(c+g,d+e);m.x=t.max(m.x,x.x,u.x,c.x);m.y=t.max(m.y,x.y,u.y,c.y);r.push("padding:0 ",n(m.x/10),"px ",n(m.y/10),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",v.join(""),", sizingmethod='clip');")}else r.push("top:",
n(m.y/10),"px;left:",n(m.x/10),"px;");r.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',10*g,"px;"," height:",10*e,'px;"',' cropleft="',f/h,'"',' croptop="',l/q,'"',' cropright="',(h-f-p)/h,'"',' cropbottom="',(q-l-k)/q,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",r.join(""))};f.stroke=function(a){var b=[],c=v(a?this.fillStyle:this.strokeStyle),d=c.color,c=c.alpha*this.globalAlpha;b.push("<g_vml_:shape",' filled="',!!a,'"',' style="position:absolute;width:',
10,"px;height:",10,'px;"',' coordorigin="0 0" coordsize="',100," ",100,'"',' stroked="',!a,'"',' path="');for(var g=null,f=null,l=null,p=null,h=0;h<this.currentPath_.length;h++){var k=this.currentPath_[h];switch(k.type){case "moveTo":b.push(" m ",n(k.x),",",n(k.y));break;case "lineTo":b.push(" l ",n(k.x),",",n(k.y));break;case "close":b.push(" x ");k=null;break;case "bezierCurveTo":b.push(" c ",n(k.cp1x),",",n(k.cp1y),",",n(k.cp2x),",",n(k.cp2y),",",n(k.x),",",n(k.y));break;case "at":case "wa":b.push(" ",
k.type," ",n(k.x-this.arcScaleX_*k.radius),",",n(k.y-this.arcScaleY_*k.radius)," ",n(k.x+this.arcScaleX_*k.radius),",",n(k.y+this.arcScaleY_*k.radius)," ",n(k.xStart),",",n(k.yStart)," ",n(k.xEnd),",",n(k.yEnd))}if(k){if(null==g||k.x<g)g=k.x;if(null==l||k.x>l)l=k.x;if(null==f||k.y<f)f=k.y;if(null==p||k.y>p)p=k.y}}b.push(' ">');if(a)if("object"==typeof this.fillStyle){var d=this.fillStyle,m=0,k=c=a=0,q=1;"gradient"==d.type_?(m=d.x1_/this.arcScaleX_,g=d.y1_/this.arcScaleY_,h=this.getCoords_(d.x0_/this.arcScaleX_,
d.y0_/this.arcScaleY_),m=this.getCoords_(m,g),m=180*Math.atan2(m.x-h.x,m.y-h.y)/Math.PI,0>m&&(m+=360),1E-6>m&&(m=0)):(h=this.getCoords_(d.x0_,d.y0_),k=l-g,q=p-f,a=(h.x-g)/k,c=(h.y-f)/q,k/=10*this.arcScaleX_,q/=10*this.arcScaleY_,h=t.max(k,q),k=2*d.r0_/h,q=2*d.r1_/h-k);g=d.colors_;g.sort(function(a,b){return a.offset-b.offset});for(var f=g.length,p=g[0].color,l=g[f-1].color,r=g[0].alpha*this.globalAlpha,x=g[f-1].alpha*this.globalAlpha,u=[],h=0;h<f;h++){var w=g[h];u.push(w.offset*q+k+" "+w.color)}b.push('<g_vml_:fill type="',
d.type_,'"',' method="none" focus="100%"',' color="',p,'"',' color2="',l,'"',' colors="',u.join(","),'"',' opacity="',x,'"',' g_o_:opacity2="',r,'"',' angle="',m,'"',' focusposition="',a,",",c,'" />')}else b.push('<g_vml_:fill color="',d,'" opacity="',c,'" />');else a=this.lineScale_*this.lineWidth,1>a&&(c*=a),b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',this.miterLimit,'"',' endcap="',e(this.lineCap),'"',' weight="',a,'px"',' color="',d,'" />');b.push("</g_vml_:shape>");
this.element_.insertAdjacentHTML("beforeEnd",b.join(""))};f.fill=function(){this.stroke(!0)};f.closePath=function(){this.currentPath_.push({type:"close"})};f.getCoords_=function(a,b){var c=this.m_;return{x:10*(a*c[0][0]+b*c[1][0]+c[2][0])-5,y:10*(a*c[0][1]+b*c[1][1]+c[2][1])-5}};f.save=function(){var a={};A(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=r(y(),this.m_)};f.restore=function(){A(this.aStack_.pop(),this);this.m_=this.mStack_.pop()};f.translate=function(a,b){h(this,r([[1,
0,0],[0,1,0],[a,b,1]],this.m_),!1)};f.rotate=function(a){var b=x(a);a=D(a);h(this,r([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};f.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;h(this,r([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};f.transform=function(a,b,c,d,e,f){h(this,r([[a,b,0],[c,d,0],[e,f,1]],this.m_),!0)};f.setTransform=function(a,b,c,d,e,f){h(this,[[a,b,0],[c,d,0],[e,f,1]],!0)};f.clip=function(){};f.arcTo=function(){};f.createPattern=function(){return new m};q.prototype.addColorStop=function(a,
b){b=v(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};G_vmlCanvasManager=G;CanvasRenderingContext2D=l;CanvasGradient=q;CanvasPattern=m}();(function(){})();
(function(z,C,u,w){function y(e,l){e.replace(/-([a-z])/g,function(e){return e[1].toUpperCase()});return l!==w?(this.style[e]=l,this):this.currentStyle?this.currentStyle[e]:this.getComputedStyle?document.defaultView.getComputedStyle(this)[e]:this.style[e]}function r(e){function l(e){return e===w?!0:e||!1}e.width=parseInt(e.width||y.call(this.dom,"width")||600);e.height=parseInt(e.height||y.call(this.dom,"height")||400);e.autoUpdate=l(e.autoUpdate);e.colors=e.colors||["red","blue","green"];e.reverseData=
e.reverseData||!1;e.marker=e.marker||"circle";e.max=e.max||1;e.yMarkerWidth=parseInt(e.yMarkerWidth||0);e.shift=l(e.shift);e.dataLength=e.dataLength||this.data.length;return e}var A={},v;u||(u={});document.createElement("canvas").getContext||(v=document.createElement("script"),v.onload=function(){},v.src="https://explorercanvas.googlecode.com/svn/trunk/silverlight/excanvas.js",document.body.appendChild(v));u.graph=function(e,l,p){var h=A[e];if(h)return h;h=new _Graph(e,l,p);return A[e]=h};_Graph=
function(e,l,p){e=z.getElementById(e)||z.querySelector(e);var h,q;e?("canvas"===e.tagName.toLowerCase()?h=e:(h=z.createElement("canvas"),h.getContext||document.createElement("script"),e.appendChild(h)),q=h.getContext("2d"),this.dom=e,this.canvas=h,this.ctx=q,this.data=l||[],l=this.data[0],l===w||l instanceof Array||(this.data=[this.data]),this.options=r.call(this,p||{}),p=this.options.width,l=this.options.height,h.width=p,h.height=l,e.style.width=p+"px",e.style.height=l+"px",this.render()):alert("Wrong dom wrapper")};
_Graph.prototype.appendData=function(e,l){var p=this.data,h=p.length,q=this.options,m,t;if(q.reverseData)p.push(e),q.shift&&h>q.dataLength&&p.splice(0,1);else for(m=0;m<h;m++)t=p[m],t.push(e[m]),q.shift&&t.length>q.dataLength&&t.splice(0,1);(l||l===w&&this.options.autoUpdate)&&this.render()};_Graph.prototype.render=function(){var e=this.data,l=e.length,p=this.options,h=p.width,q=p.height,m=this.ctx,t,n,r,u=p.yMarkerWidth,v=q/p.max,w=p.dataLength;m.clearRect(0,0,h,q);for(t=l;t--;)if(l=e[t],q=l.length,
0<q){r=(h-u)/w;m.strokeStyle=p.colors[t];m.beginPath();m.moveTo(u,v*l[0]);for(n=1;n<q;n++)m.lineTo(u+r*n,v*l[n]);m.stroke()}};C.VJ=u})(document,window,window.VJ);(function(){})();
